name: vyra_verse
description: "VyRaVerse - A next-generation social media platform"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.8.2
  chewie: ^1.7.4
  visibility_detector: ^0.4.0+2
  flutter_cache_manager: ^3.3.1
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  just_audio: ^0.9.40
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2
  image_picker: ^1.0.7
  http: ^1.2.0
  share_plus: ^7.2.2
  mime: ^1.0.4
  http_parser: ^4.0.2
  path: ^1.8.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  camera: ^0.10.5+5
  image: ^4.1.3
  saver_gallery: ^3.0.3
  geolocator: ^10.1.0
  fl_chart: ^0.66.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  win32: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splashh.jpg
    - assets/images/default_profile.gif
    - assets/lottie/chat.json
    - assets/sounds/
